import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          style={{ height: "100vh" }}
          className="bg-[url('../public/333950.jpg')] bg-cover bg-bottom flex justify-center items-center flex-col"
        >
          <div className="absolute mb-96">
            <Image src="/../public/logo.png"  width={500} height={500} />
          </div>
          <form action="" className="flex">
            <div>
              <input 
              placeholder='Ash Ketchum' 
              style={{height:'5vh', width:'20vw', borderRadius:'50px 0px 0px 50px', padding:'20px'}} 
              type="text"
              />
            </div>
            <div>
              <button
                style={{height:'5vh', width:'4vw', backgroundColor:'white', borderRadius:'0px 50px 50px 0px'}}
                className="hover:bg-slate-300"
              >
                <p>Go</p>
              </button>
            </div>
          </form>
        </div>
      </main>
    </>
  );
}
